### ISSUE TITLE
Data Scraping for the GTA region from housing Sigma

### ISSUE THREAD

**Issue by Bavalpreet** [Bavalpreet/Ilore-AI-Assisted-Property-Search-System#12]
In this, we will be scraping the details for all the listins under the GTA region. Two files will be curated:-
- csv containing all the listed ids along with corresponsing descriptions.
- JSON response for every id listed containg whole meta dara as well.

**Comment by YashiSikligar** [comment]
[Description_dataset.csv](https://github.com/Bavalpreet/Ilore-AI-Assisted-Property-Search-System/files/14500300/Description_dataset.csv)
The above file contains a dataset comprising descriptions of properties located in the Greater Toronto Area (GTA), alongside their respective listing IDs. This dataset will serve as the foundation for constructing a vector database, a crucial step in further data processing.

**Comment by anand246** [comment]
completed fetching all meta data from each City in GTA region 

Used the Suggest API for getting each city 

"https://housesigma.com/bkv2/api/search/address_v2/suggest"

used 
gta_cities = [
    "Toronto", "Ajax", "Aurora", "Brampton", "Brock", "Burlington",
    "Caledon", "Clarington", "East Gwillimbury", "Georgina", "Markham",
    "Mississauga", "Milton", "Newmarket", "Oakville", "Oshawa", "Pickering",
    "Richmond Hill", "Scugog", "Vaughan", "Whitchurch-Stouffville", "Uxbridge",
    "King", "Halton Hills", "Whitby"
]

these as city names and stored as json then stored all the ids  and fetch the discription
