### ISSUE TITLE
Create the vector index and push the data to the vector db

### ISSUE THREAD

**Issue by Bavalpreet** [Bavalpreet/Ilore-AI-Assisted-Property-Search-System#13]
After succesfull data scraping all the ids and descriptions will be pushed to vector db. for future use.

**Comment by Yatharth08** [comment]
[des1_des2_pinecone.zip](https://github.com/Bavalpreet/Ilore-AI-Assisted-Property-Search-System/files/14500773/des1_des2_pinecone.zip)
